
{{- if and .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cipms.fullname" . }}-env
  labels:
    {{- include "cipms.labels" . | nindent 4 }}
type: Opaque
data: 
  {{- range $key, $value := .Values.envSecrets }}
    {{ $key }}: {{ $value | b64enc -}}
  {{ end }}
{{- end }}