apiVersion: v1
kind: Service
metadata:
  name: {{ include "cipms.fullname" . }}
  labels:
    {{- include "cipms.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "cipms.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cipms.selectorLabels" . | nindent 4 }}
