imagePullSecrets:
  - name: vsmreg

envSecrets: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi

service:
  enabled: true
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: local
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: awsdaotq.net
      paths:
        - path: /apps/pms(/|$)(.*)
          pathType: Prefix
